### ISSUE TITLE
同期描画でのフリーズ問題

### ISSUE THREAD

**Issue by cosmo0920** [webdino/gecko-embedded#62]
EGL有効化時にOpenGLコンポジターを有効にするとfirefoxが立ち上がらない。
同期描画ではなく、非同期描画にするとsubsurfaceへの描画が開始され、firefoxが立ち上がる。

see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1464823

**Comment by cosmo0920** [comment]
上記のBugではMesaのEGLドライバにバグがあるようだが、RZ/G1M・R-Car M3のEGLドライバにも同様のバグがある模様。

Mesaについては以下にバグ報告されている。
https://bugs.freedesktop.org/show_bug.cgi?id=106753

**Comment by cosmo0920** [comment]
こちらは本当の原因はFirerfoxのWaylandの実装にあるようだ。
https://bugs.freedesktop.org/show_bug.cgi?id=106753#c6

**Comment by cosmo0920** [comment]
一旦 @ashie さんのパッチをfdirefox-60esrに投入してみる。
https://github.com/webdino/meta-browser/commit/a3cb615cc166b48dec10e51956e9755fe9f3bb29

**Comment by ashie** [comment]
PC版では

* https://bugzilla.mozilla.org/show_bug.cgi?id=1464823

でいったん解決しているが、RZ/G に同じパッチを投入するとクラッシュする。
この件については以下にバグを立ててある。

* https://bugzilla.mozilla.org/show_bug.cgi?id=1468907

本プロジェクトとしては

> 一旦 @ashie さんのパッチをfirefox-60esrに投入してみる。
> webdino/meta-browser@a3cb615

で動作しているので、こちらもクローズし、続きは上記Bugにて。
