### ISSUE TITLE
R-Car M3向けのYocto BSPでStyloのビルドを成功させる

### ISSUE THREAD

**Issue by cosmo0920** [webdino/gecko-embedded#67]
#66 の後、または、rust-llvmのインストール先を変更するパッチを取り込んだ後でないとこのIssueは動けない。
meta-clangでlibclang.soをインストールできるようになればYoctoですべて完結するため、Styloのビルドの道が開けるはず。

**Comment by cosmo0920** [comment]
また、表題にはR-Car M3と付けたが、Yocto 2.4を採用したBSPを扱ってのStyloのビルドにも高い確度でこのIssueの対応は必須になる見込み。

**Comment by ashie** [comment]
有効化できた。
魚拓:

![stylo-aarch64](https://user-images.githubusercontent.com/135104/48696508-770bb080-ec25-11e8-80c4-d4d286c39f9a.png)

いまのレシピだとincludeパスの指定が適当すぎるので、その辺をもう少し整理する必要がある。

**Comment by cosmo0920** [comment]
clang/llvm 3.9縛りが消えた気がするのでclang/llvm 4.0でビルド確認中。

**Comment by cosmo0920** [comment]
clang/llvm 4.0でもビルドできるようになってました。

**Comment by ashie** [comment]
修正をpushしたのでクローズします。

https://github.com/webdino/meta-browser/commit/a78ae6465516aa2be6d6b790d3bdb25d7bc7b648

> clang/llvm 4.0でもビルドできるようになってました。

この辺り何かやるのであれば、別issue立ててそちらでお願いします。
