### ISSUE TITLE
meta-browser: ビルドドキュメント更新

### ISSUE THREAD

**Issue by ashie** [webdino/gecko-embedded#68]
最近の[webdio/meta-browser](https://github.com/webdino/meta-browser/)は[フォーク版のmeta-rust](https://github.com/meta-rust/meta-rust/pull/208)を必要としていたが、[OSSystems/meta-browser](https://github.com/OSSystems/meta-browser)の方でRustのビルド問題が直ったので、アップストリーム版の[meta-rust/met-rust](https://github.com/meta-rust/meta-rust)で問題なくビルドが通るようになった。

また、meta-browserについても基本的には全てアップストリームである[OSSystems/meta-browser](https://github.com/OSSystems/meta-browser)にマージ済みなので、ESR60に関して言えば、フォーク版のmeta-browserやmeta-rustは役割を終えつつある。とはいえまだこちらを参照しているユーザーもいるようなので、当面はこのまま置いておく。

新規ユーザーについてはアップストリーム版に誘導したいので、[ビルド手順書](https://github.com/webdino/meta-browser/wiki)をそのように更新しておきたい。

**Comment by dynamis** [comment]
多分もう Wiki の方は更新せずプロジェクトサイト作成 (#71) 時に移転やリポジトリの方に書くなどが増えていくのでこちらはクローズしてしまいます。
