### ISSUE TITLE
RZ/G: ウィンドウリサイズ時などに Weston/Gecko のクラッシュやフリーズする

### ISSUE THREAD

**Issue by dynamis** [webdino/gecko-embedded#72]
当初からの問題だが、Renesas RZ/G1,2 向けのビルドでウィンドウリサイズ時にフリーズすることがある。

用途的にウィンドウ起動の必要性がない場合が多いため、ウィンドウ利用はサポート外として kiosk パッチ (フルスクリーン固定起動) を入れてビルドしている状態:
https://github.com/webdino/meta-browser/tree/firefox-60esr/recipes-browser/firefox/firefox/wayland/kiosk

**Comment by ashie** [comment]
RZ/G1ではフリーズではなくてクラッシュという形で発生します。

以下と同じ問題か？（仕様バグでは？的な話）
https://bugs.freedesktop.org/show_bug.cgi?id=105507

**Comment by dynamis** [comment]
about:config で数字の設定値を変更するダイアログを出し、OK ボタンではなく Enter キーで閉じる場合もフリーズする (Gecko 68 on RZ/G2E などで 100% 再現)。なお、設定値の変更は反映されるし、OK ボタンで閉じる場合はフリーズしない。

**Comment by dynamis** [comment]
あくまで Firefox ブラウザビルドを使ってるときにのみ発生する問題であるし、後続バージョンでは安定化が進み解決している問題であるので、旧バージョンでの制約事項として wontfix クローズします。
