### ISSUE TITLE
Gecko 68 で about:support ページがクラッシュする

### ISSUE THREAD

**Issue by dynamis** [webdino/gecko-embedded#88]
Gecko 68 対応のビルドが出来るようになったが about:support がクラッシュする。
コンテンツの表示をする上では問題にならないが動作状況・設定の確認のために便利なので出来れば修正したい問題。

これまでの調査状況について詳しくはこちら:
https://github.com/webdino/gecko-embedded/issues/70#issuecomment-518089074

**Comment by ashie** [comment]
OSSystems/meta-browser にて対応済みです。

https://github.com/OSSystems/meta-browser/pull/294

**Comment by dynamis** [comment]
@ashie あー、そうでした。何処かで対応済みと書いてあった気がするのにおかしいな...と思っていたのです。ありがとうございますっ！

**Comment by anyakichi** [comment]
Gecko 68 のビルドでは OSSystems/meta-browser をそのままベースに使うようにしたので、本件については実質的に解決済み。

**Comment by dynamis** [comment]
note: gem-firefox-68.0.0esr ブランチが OSSystems/meta-browser ベース:
https://github.com/webdino/meta-browser/tree/gem-firefox-68.0.0esr
