### ISSUE TITLE
RZ/G2E で FPS オーバーレイ表示が出来ない

### ISSUE THREAD

**Issue by dynamis** [webdino/gecko-embedded#97]
RZ/G2E 環境で layers.acceleration.draw-fps=true にしても FPS を表示するオーバーレイが表示されない。たまにずれたところに表示されることはあるが継続的に現在のタブの FSP を表示できている状態ではない。

コンテンツの表示環境としては問題ない・関係ない、オマケ機能の部分なので優先度は低いが、パフォーマンス確認で便利な機能が動作しないのは少し不便。

**Comment by yoshikuni-kamimiya** [comment]
RZ/G2E x VLP1.0.2 x Gecko68環境で” layers.acceleration.draw-fps=true ”でFPS見れました。現在もFPS見れないでしょうか？
![wayland-screenshot](https://user-images.githubusercontent.com/49438697/82005568-a0818d00-96a0-11ea-857b-62deb6348055.png)

**Comment by dynamis** [comment]
閉じ忘れていました。一時期のビルドでは再現していたがいつからか解消していた問題ですのでクローズします。
